# Generated by Django 4.2.1 on 2023-08-26 08:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0002_alter_chatroom_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRoom',
            new_name='Chat',
        ),
    ]
